import Head from "next/head";
import Cursor from "../components/Cursor/Cursor";
import Hero from "../components/Hero/Hero";
import Navigation from "../components/Navigation/Navigation";
import ParticlesContainer from "../components/Particles/Particles";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Joshua Dinhs Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParticlesContainer />
      <Cursor />
      <Navigation />
      <Hero />
    </>
  );
}
