import React, { useState } from "react";
import Head from "next/head";
import Cursor from "../components/Cursor/Cursor";
import Hero from "../components/Hero/Hero";
import Navigation from "../components/Navigation/Navigation";
import ParticlesContainer from "../components/Particles/Particles";
import Projects from "../components/Projects/Projects";
import About from "../components/About/About";
import Svg from "../components/Svg/Svg";
import Contact from "../components/Contact/Contact";
import MobileNavigation from "../components/MobileNavigation/MobileNavigation";
import Footer from "../components/Footer/Footer";

export default function Home() {
  const [hover, setHover] = useState(false);

  return (
    <>
      <Head>
        <title>Joshua Dinhs Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap');
        </style>
      </Head>
      <ParticlesContainer />
      <Cursor />
      <Svg />
      <Navigation />
      <MobileNavigation />
      <Hero />
      <About />
      <Projects />
      <Contact />
      <Footer />
    </>
  );
}
